const promise = new Promise((resolve, reject) => {
  if (condicao) {
    resolve("resolvido!"); // dado Ã© retornado para o then
  } else {
    reject("aaahh errooou"); // entra no catch
  }
});

promise
  .then((data) => {
    console.log(data);
  })
  .catch((err) => {
    console.log(err);
  });
